INSERT INTO PUBLIC.ETUDIANT (ID, IDFORMATION) VALUES (3, 1);
INSERT INTO PUBLIC.ETUDIANT (ID, IDFORMATION) VALUES (6, 1);
INSERT INTO PUBLIC.ETUDIANT (ID, IDFORMATION) VALUES (26, 1);
INSERT INTO PUBLIC.ETUDIANT (ID, IDFORMATION) VALUES (4, 2);
