INSERT INTO PUBLIC.MATIERE (NOMMATIERE, IDFORMATION) VALUES ('Programmation avancée', 1);
INSERT INTO PUBLIC.MATIERE (NOMMATIERE, IDFORMATION) VALUES ('Réseaux informatiques', 1);
INSERT INTO PUBLIC.MATIERE (NOMMATIERE, IDFORMATION) VALUES ('Calcul différentiel', 2);
INSERT INTO PUBLIC.MATIERE (NOMMATIERE, IDFORMATION) VALUES ('Algèbre linéaire', 2);
INSERT INTO PUBLIC.MATIERE (NOMMATIERE, IDFORMATION) VALUES ('Protection des données', 1);
INSERT INTO PUBLIC.MATIERE (NOMMATIERE, IDFORMATION) VALUES ('Bases de l''apprentis', 1);
INSERT INTO PUBLIC.MATIERE (NOMMATIERE, IDFORMATION) VALUES ('Mécanique quantique', 2);
