INSERT INTO PUBLIC.SALLE (NOMBREPLACE, NOMSALLE) VALUES (45, 'E5');
INSERT INTO PUBLIC.SALLE (NOMBREPLACE, NOMSALLE) VALUES (55, 'F6');
INSERT INTO PUBLIC.SALLE (NOMBREPLACE, NOMSALLE) VALUES (25, 'G7');
INSERT INTO PUBLIC.SALLE (NOMBREPLACE, NOMSALLE) VALUES (35, 'H8');
INSERT INTO PUBLIC.SALLE (NOMBREPLACE, NOMSALLE) VALUES (70, 'I9');
INSERT INTO PUBLIC.SALLE (NOMBREPLACE, NOMSALLE) VALUES (20, 'J10');
INSERT INTO PUBLIC.SALLE (NOMBREPLACE, NOMSALLE) VALUES (50, 'K11');
INSERT INTO PUBLIC.SALLE (NOMBREPLACE, NOMSALLE) VALUES (60, 'L12');
